### PR TITLE
User buildozer from master branch, including the following fix: https…

### PR DESCRIPTION
**Pull request by guysoft**
User buildozer from master branch, including the following fix
Without it my builds fail because of this bug:
https://github.com/kivy/buildozer/issues/649

Solution was merged here:
https://github.com/kivy/buildozer/issues/700

### CODE REVIEW

**Comment by JonasT** [comment]
@guysoft actually I'd rather go with p4a to a stable or at least a pinned version per default, it's just not very feasible given how broken the latest stable release is. (master has moved pretty fast with lots of improvements the last 1-2 months) So I'm not sure if it's a good idea to move to even more experimental branches... buildozer especially has a quicker release cycle, doesn't it? Might be a better idea to just get an update release instead

I see where you are coming from though, defaulting to p4a master is prone to cause issues with buildozer. I'll have to think about this, I find it really hard to decide what is the best default here (dev version or latest stable) given how the situation is right now...

**Comment by AndreMiras** [comment]
Release cycle is something I want to discuss with the team in the coming weeks. Ideally I would like a release early release often, but let's see what comes out

**Comment by JonasT** [comment]
@guysoft for what it's worth, `pip3 install --user -U https://github.com/kivy/buildozer/archive/master.zip` (or respectively `pip2 install --user -U https://github.com/kivy/buildozer/archive/master.zip` for the python 2-based environments) should work now, even when using `--map-to-user` with a non-root user for reduced privileges

**Comment by JonasT** [comment]
Given there is now `--buildozer` to specify the buildozer version (which can be set to `master` for the latest git master) it appears to me that this pull request is no longer necessary. Thanks for your input which made me add that option :smile: and feel free to poke me if you see a need to reopen this, I'll close it for now

**Pull request closed without merging**
